version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - queue-microservice
    volumes: 
      - rabbitmq:/data/rebbitmq

networks:
  queue-microservice:
    driver: bridge

volumes:
  rabbitmq:
    driver: local